- id: '1727566814378'
  alias: Privacy after sunsset
  description: ''
  triggers:
  - event: sunset
    offset: -00:10:00
    trigger: sun
  conditions: []
  actions:
  - action: cover.close_cover
    metadata: {}
    data: {}
    target:
      label_id: privacy
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      label_id: exterior_lights
  mode: single
- id: '1727619363042'
  alias: Open shades in the morning
  description: ''
  trigger:
  - platform: time
    at: 08:00:00
  condition: []
  action:
  - action: cover.set_cover_position
    metadata: {}
    data:
      position: 50
    target:
      area_id:
      - kitchen
      - office
  - action: cover.open_cover
    metadata: {}
    data: {}
    target:
      area_id:
      - dining_room
      - flex_room
  mode: single
- id: '1740363545295'
  alias: Night Lockup
  description: ''
  triggers:
  - trigger: time
    at: '23:00:00'
  conditions: []
  actions:
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      label_id: exterior_lights
  mode: single
