- id: "1727566814378"
  alias: Privacy after sunsset
  description: ""
  triggers:
    - event: sunset
      offset: -00:10:00
      trigger: sun
  conditions: []
  actions:
    - action: cover.close_cover
      metadata: {}
      data: {}
      target:
        label_id: privacy
    - action: switch.turn_on
      metadata: {}
      data: {}
      target:
        label_id: exterior_lights
  mode: single
- id: "1727619363042"
  alias: Open shades in the morning
  description: ""
  trigger:
    - platform: time
      at: 08:00:00
  condition: []
  action:
    - action: cover.set_cover_position
      metadata: {}
      data:
        position: 50
      target:
        area_id:
          - kitchen
          - office
    - action: cover.open_cover
      metadata: {}
      data: {}
      target:
        area_id:
          - dining_room
          - flex_room
  mode: single
- id: "1733696274738"
  alias: Turn on Xmas lights at sundown
  description: ""
  trigger:
    - platform: sun
      event: sunset
      offset: -00:10:00
  condition: []
  action:
    - type: turn_on
      device_id: bae8944e9df850d8d0739e306357e229
      entity_id: c4972189d6aab967cd72ec004b3e8b00
      domain: switch
    - type: turn_on
      device_id: 9f3363e82a72b23e1da7bf737f093707
      entity_id: 241e0be30ebbc15fe022d7e154ce88a6
      domain: switch
  mode: single
- id: "1733696356437"
  alias: Turn off Xmas Lights at 11
  description: ""
  triggers:
    - at: "23:00:00"
      trigger: time
  conditions: []
  actions:
    - type: turn_off
      device_id: bae8944e9df850d8d0739e306357e229
      entity_id: c4972189d6aab967cd72ec004b3e8b00
      domain: switch
    - type: turn_off
      device_id: 9f3363e82a72b23e1da7bf737f093707
      entity_id: 241e0be30ebbc15fe022d7e154ce88a6
      domain: switch
  mode: single
- id: "1736729071588"
  alias: Turn off heat mats after 4h
  description: ""
  triggers:
    - type: turned_on
      device_id: 41d526899fcd5a046a93f31ff8e68c95
      entity_id: a19db08a70cc0f17f9cb1498921b491f
      domain: switch
      trigger: device
      for:
        hours: 4
        minutes: 0
        seconds: 0
  conditions: []
  actions:
    - type: turn_off
      device_id: 41d526899fcd5a046a93f31ff8e68c95
      entity_id: a19db08a70cc0f17f9cb1498921b491f
      domain: switch
  mode: single
- id: "1739554002605"
  alias: Back Office switch on
  description: ""
  triggers:
    - type: turned_on
      device_id: 63096b2560edc00b3941c2e69a672b69
      entity_id: 3e5731b2bd377e8551f9f8cbfbb9dec8
      domain: switch
      trigger: device
  conditions: []
  actions:
    - type: turn_on
      device_id: 78a3b8510d0deb606138f8f225ce70da
      entity_id: 4db8578a0a8cac4f29b12700f374c3bc
      domain: light
      brightness_pct: 100
  mode: single
- id: "1739554090985"
  alias: Back Office switch off
  description: ""
  triggers:
    - type: turned_off
      device_id: 63096b2560edc00b3941c2e69a672b69
      entity_id: 3e5731b2bd377e8551f9f8cbfbb9dec8
      domain: switch
      trigger: device
  conditions: []
  actions:
    - type: turn_off
      device_id: 78a3b8510d0deb606138f8f225ce70da
      entity_id: 4db8578a0a8cac4f29b12700f374c3bc
      domain: light
  mode: single
- id: "1740363545295"
  alias: Night Lockup
  description: ""
  triggers:
    - trigger: time
      at: "23:00:00"
  conditions: []
  actions:
    - action: switch.turn_off
      metadata: {}
      data: {}
      target:
        label_id: exterior_lights
  mode: single
