- id: '1727566814378'
  alias: Privacy after sunsset
  description: ''
  triggers:
  - event: sunset
    offset: -00:10:00
    trigger: sun
  conditions: []
  actions:
  - action: cover.close_cover
    metadata: {}
    data: {}
    target:
      label_id: privacy
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      label_id: exterior_lights
  mode: single
- id: '1727619363042'
  alias: Open shades in the morning
  description: ''
  trigger:
  - platform: time
    at: 08:00:00
  condition: []
  action:
  - action: cover.set_cover_position
    metadata: {}
    data:
      position: 50
    target:
      area_id:
      - kitchen
      - office
  - action: cover.open_cover
    metadata: {}
    data: {}
    target:
      area_id:
      - dining_room
      - flex_room
  mode: single
- id: '1740363545295'
  alias: Night Lockup
  description: ''
  triggers:
  - trigger: time
    at: '23:00:00'
  conditions: []
  actions:
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      label_id: exterior_lights
  mode: single
- id: '1764032833582'
  alias: Back Office Auto Link Switch
  description: ''
  use_blueprint:
    path: auto_link_switch.yaml
    input:
      source_switch: switch.back_office_lightswitch
      linked_entities:
      - switch.back_office_wall_lights_outlet
- id: '1764033059754'
  alias: Back Patio Auto Link Switch
  description: ''
  use_blueprint:
    path: auto_link_switch.yaml
    input:
      source_switch: switch.back_patio_switch
      linked_entities:
      - switch.back_patio_string_lights
- id: '1764043939005'
  alias: Kitchen Pantry Auto Door Lights
  description: ''
  use_blueprint:
    path: auto_door_lights.yaml
    input:
      trigger_sensors:
      - binary_sensor.kitchen_pantry_door
      target_lights:
      - switch.kitchen_pantry_light_switch
- id: '1764044002889'
  alias: Mudroom Auto Door Lights
  description: ''
  use_blueprint:
    path: auto_door_lights.yaml
    input:
      trigger_sensors:
      - binary_sensor.mudroom_closet_door
      target_lights:
      - switch.mudroom_closet_light_switch
- id: ups_emergency_shutdown
  alias: UPS Emergency Shutdown
  description: Shutdown HA and NAS when UPS battery drops below 20%
  triggers:
  - trigger: numeric_state
    entity_id:
    - sensor.rack_ups_battery_charge
    below: 20
  conditions:
  - condition: template
    value_template: '{{ ''On Battery'' in states(''sensor.cyberpower_network_ups_status'')
      }}

      '
  actions:
  - action: notify.p1_critical
    data:
      title: "\U0001FAAB UPS battery critical - shutting down"
      message: Battery at {{ states('sensor.cyberpower_network_ups_battery_charge',
        rounded=True, with_unit=True) }} - Initiating emergency shutdown
      data:
        tag: p1_ups_critical
        subtitle: Lavender Circle
        group: ha
        push:
          interruption-level: critical
        url: /1-system/alerts
  - action: synology_dsm.shutdown
  - delay:
      seconds: 10
  - action: hassio.host_shutdown
  mode: single
- id: back_patio_auto_heat_mats_off
  alias: Back Patio Auto Heat Mats Off
  description: Turn off heat mats automatically
  triggers:
  - trigger: state
    entity_id:
    - switch.back_patio_heat_mats
    to: 'on'
    for:
      hours: 3
      minutes: 0
      seconds: 0
  actions:
  - action: switch.turn_off
    target:
      entity_id: switch.back_patio_heat_mats
  mode: restart
- id: '1764180137952'
  alias: Garage Auto Door Lights
  description: ''
  use_blueprint:
    path: auto_door_lights.yaml
    input:
      trigger_sensors:
      - binary_sensor.alarm_panel_garage_door
      - cover.garage_single_garage_door
      - cover.garage_double_garage_door
      target_lights:
      - switch.garage_lights
- id: '1764188190717'
  alias: Double Garage Auto Cover Close
  description: ''
  use_blueprint:
    path: auto_cover_close.yaml
    input:
      target: cover.garage_double_garage_door
      target_lock: lock.garage_double_lock
      target_obstruction: binary_sensor.garage_double_obstruction
- id: '1764188222075'
  alias: Single Garage Auto Cover Close
  description: ''
  use_blueprint:
    path: auto_cover_close.yaml
    input:
      target: cover.garage_single_garage_door
      target_lock: lock.garage_single_lock
      target_obstruction: binary_sensor.garage_single_obstruction
- id: '1764196300661'
  alias: Force close idle garage doors
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - cover.garage_doors
    for:
      hours: 0
      minutes: 30
      seconds: 0
    to: open
  conditions: []
  actions:
  - repeat:
      while:
      - condition: state
        entity_id: cover.garage_doors
        state: open
      sequence:
      - action: script.force_garage_doors_closed
        metadata: {}
        data: {}
      - delay:
          hours: 0
          minutes: 30
          seconds: 0
          milliseconds: 0
  mode: restart
- id: '1764293728906'
  alias: Theater Lighting
  description: ''
  triggers:
  - alias: Theater AppleTV is playing
    trigger: state
    id: playing
    entity_id:
    - media_player.home_theater
    to: playing
    for:
      hours: 0
      minutes: 0
      seconds: 2
  - trigger: state
    alias: Theater AppleTV is paused/idle
    id: pause
    entity_id:
    - media_player.home_theater
    to:
    - paused
    - idle
    not_from:
    - unknown
    for:
      seconds: 2
  - trigger: state
    alias: Theater AppleTV is off
    id: standby
    entity_id:
    - media_player.home_theater
    to:
    - standby
    - 'off'
    not_from:
    - unknown
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - playing
      sequence:
      - action: scene.turn_on
        metadata: {}
        data:
          transition: 4
        target:
          entity_id: scene.theater_lights_playing
    - conditions:
      - condition: trigger
        id:
        - pause
      sequence:
      - action: scene.turn_on
        metadata: {}
        data:
          transition: 4
        target:
          entity_id: scene.theater_lights_paused
    - conditions:
      - condition: trigger
        id:
        - standby
      sequence:
      - action: scene.turn_on
        metadata: {}
        data:
          transition: 4
        target:
          entity_id: scene.theater_lights_full
  mode: single
- id: '1764639787851'
  alias: Notify Laundry Finished
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.washing_machine_status
    from: 'on'
    to: 'off'
  - trigger: state
    entity_id:
    - binary_sensor.dryer_status
    to: 'off'
    from: 'on'
  conditions:
  - condition: and
    conditions:
    - condition: state
      entity_id: binary_sensor.washing_machine_status
      state: 'off'
    - condition: state
      entity_id: binary_sensor.dryer_status
      state: 'off'
  actions:
  - action: script.notify_home
    metadata: {}
    data:
      title: Laundry finished
      message: Finished at {{ ([ states.binary_sensor.washing_machine_status.last_changed
        , states.binary_sensor.dryer_status.last_changed ] | max).strftime('%a %b
        %-d, %-I:%M %p') }}
  mode: single
