---
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  packages: !include_dir_named packages

################################################################################
# UI Configuration
################################################################################
lovelace:
  mode: storage

  resources:
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module

  ##############################################################################
  dashboards:
    lvndr-0:
      mode: yaml
      title: LVNDR
      filename: ui/dashboards/lvndr-dashboard.yaml
