---
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  # @see https://github.com/thomasloven/lovelace-card-mod#performance-improvements
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js?hacstag=12345678901

zha:
  zigpy_config:
    ota:
      otau_directory: /config/zb_ota_auto_update
      extra_providers: [{'type': 'thirdreality'}]

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  packages: !include_dir_named packages

################################################################################
# UI Configuration
################################################################################
lovelace:
  mode: storage
