### Main Dashboard ###

title: Home
icon: mdi:home

button_card_templates:
  control_toggle: !include ui/templates/control-toggle.yaml

views:
  - !include ui/views/home-view.yaml
  - !include ui/views/control-view.yaml
