# Climate Monitor
# General
#
# Trigger alerts if climate sensors are outside of normal ranges
---

#
# Device Configuration
#
homeassistant:
  customize:
    package.node_anchors:
      pkg: &package
        package: general/climate_monitor

    #
    # Programmatic entities defined in this package
    #
    alert.p1_climate_temp:
      <<: *package
    alert.p1_climate_humidity:
      <<: *package
    alert.p2_climate_temp:
      <<: *package
    alert.p2_climate_humidity:
      <<: *package
    binary_sensor.p1_climate_temp_trigger:
      <<: *package
    binary_sensor.p1_climate_humidity_trigger:
      <<: *package
    binary_sensor.p2_climate_temp_trigger:
      <<: *package
    binary_sensor.p2_climate_humidity_trigger:
      <<: *package

template:
  - binary_sensor:

      #
      # Critical climate temperature trigger
      #
      - name: p1_climate_temp_trigger
        state: "{{ this.attributes.get('entities', []) | count > 0 }}"
        availability: >
          {% from 'labeled_all_entities.jinja' import labeled_all_entities %}
          {% set all_entities = labeled_all_entities('Climate', as_array) %}
          {{ states
            | selectattr('entity_id', 'in', all_entities)
            | selectattr('attributes.device_class', 'eq', 'temperature')
            | rejectattr('state', 'in', ['unknown', 'unavailable', 'none'])
            | list | count > 0 }}
        attributes:
          device_class: problem
          entities: >
            {% from 'labeled_all_entities.jinja' import labeled_all_entities %}
            {% set all_entities = labeled_all_entities('Climate', as_array) %}
            {% set ns = namespace(entities=[]) %}
            {% for entity in states.sensor
              | selectattr('entity_id', 'in', all_entities)
              | selectattr('attributes.device_class', 'eq', 'temperature')
              | rejectattr('state', 'in', ['unknown', 'unavailable', 'none']) %}
              {% set temp = states(entity.entity_id) | float(-1) %}
              {% if temp > 80.0 or temp < 60.0 %}
                {% set ns.entities = ns.entities + [entity.entity_id] %}
              {% endif %}
            {% endfor %}
            {{ ns.entities }}
          message: >
            {% set entities = this.attributes.get('entities', []) %}
            {% set entity_count = entities | count %}
            {% set entity_first = entities | first | default('') %}
            {% if entity_count == 0 %}All zones normal
            {% elif entity_count == 1 %}{{ state_attr(entity_first, 'friendly_name') }} is {{ states(entity_first, rounded=True, with_unit=True) }}
            {% else %}{{ state_attr(entity_first, 'friendly_name') }} ({{ states(entity_first, rounded=True, with_unit=True) }}) and {{ entity_count - 1 }} others are critical temperature
            {% endif %}
          source_entity_id: "{{ this.entity_id }}"
          title: "🌡️ Temperature CRITICAL"

      #
      # Warning climate temperature trigger
      #
      - name: p2_climate_temp_trigger
        state: "{{ this.attributes.get('entities', []) | count > 0 }}"
        availability: >
          {% from 'labeled_all_entities.jinja' import labeled_all_entities %}
          {% set all_entities = labeled_all_entities('Climate', as_array) %}
          {{ states
            | selectattr('entity_id', 'in', all_entities)
            | selectattr('attributes.device_class', 'eq', 'temperature')
            | rejectattr('state', 'in', ['unknown', 'unavailable', 'none'])
            | list | count > 0 }}
        attributes:
          device_class: problem
          entities: >
            {% from 'labeled_all_entities.jinja' import labeled_all_entities %}
            {% set all_entities = labeled_all_entities('Climate', as_array) %}
            {% set ns = namespace(entities=[]) %}
            {% for entity in states.sensor
              | selectattr('entity_id', 'in', all_entities)
              | selectattr('attributes.device_class', 'eq', 'temperature')
              | rejectattr('state', 'in', ['unknown', 'unavailable', 'none']) %}
              {% set temp = states(entity.entity_id) | float(-1) %}
              {% if temp > 75.0 or temp < 63.0 %}
                {% set ns.entities = ns.entities + [entity.entity_id] %}
              {% endif %}
            {% endfor %}
            {{ ns.entities }}
          message: >
            {% set entities = this.attributes.get('entities', []) %}
            {% set entity_count = entities | count %}
            {% set entity_first = entities | first | default('') %}
            {% if entity_count == 0 %}All zones normal
            {% elif entity_count == 1 %}{{ state_attr(entity_first, 'friendly_name') }} is {{ states(entity_first, rounded=True, with_unit=True) }}
            {% else %}{{ state_attr(entity_first, 'friendly_name') }} ({{ states(entity_first, rounded=True, with_unit=True) }}) and {{ entity_count - 1 }} others are warning temperature
            {% endif %}
          source_entity_id: "{{ this.entity_id }}"
          title: "🌡️ Temperature Warning"

      #
      # Critical climate humidity trigger
      #
      - name: p1_climate_humidity_trigger
        state: "{{ this.attributes.get('entities', []) | count > 0 }}"
        availability: >
          {% from 'labeled_all_entities.jinja' import labeled_all_entities %}
          {% set all_entities = labeled_all_entities('Climate', as_array) %}
          {{ states
            | selectattr('entity_id', 'in', all_entities)
            | selectattr('attributes.device_class', 'eq', 'humidity')
            | rejectattr('state', 'in', ['unknown', 'unavailable', 'none'])
            | list | count > 0 }}
        attributes:
          device_class: problem
          entities: >
            {% from 'labeled_all_entities.jinja' import labeled_all_entities %}
            {% set all_entities = labeled_all_entities('Climate', as_array) %}
            {% set ns = namespace(entities=[]) %}
            {% for entity in states.sensor
              | selectattr('entity_id', 'in', all_entities)
              | selectattr('attributes.device_class', 'eq', 'humidity')
              | rejectattr('state', 'in', ['unknown', 'unavailable', 'none']) %}
              {% set humidity = states(entity.entity_id) | float(-1) %}
              {% if humidity > 90.0 or humidity < 10.0 %}
                {% set ns.entities = ns.entities + [entity.entity_id] %}
              {% endif %}
            {% endfor %}
            {{ ns.entities }}
          message: >
            {% set entities = this.attributes.get('entities', []) %}
            {% set entity_count = entities | count %}
            {% set entity_first = entities | first | default('') %}
            {% if entity_count == 0 %}All zones normal
            {% elif entity_count == 1 %}{{ state_attr(entity_first, 'friendly_name') }} is {{ states(entity_first, rounded=True, with_unit=True) }}
            {% else %}{{ state_attr(entity_first, 'friendly_name') }} ({{ states(entity_first, rounded=True, with_unit=True) }}) and {{ entity_count - 1 }} others are critical humidity
            {% endif %}
          source_entity_id: "{{ this.entity_id }}"
          title: "💧 Humidity CRITICAL"

      #
      # Warning climate humidity trigger
      #
      - name: p2_climate_humidity_trigger
        state: "{{ this.attributes.get('entities', []) | count > 0 }}"
        availability: >
          {% from 'labeled_all_entities.jinja' import labeled_all_entities %}
          {% set all_entities = labeled_all_entities('Climate', as_array) %}
          {{ states
            | selectattr('entity_id', 'in', all_entities)
            | selectattr('attributes.device_class', 'eq', 'humidity')
            | rejectattr('state', 'in', ['unknown', 'unavailable', 'none'])
            | list | count > 0 }}
        attributes:
          device_class: problem
          entities: >
            {% from 'labeled_all_entities.jinja' import labeled_all_entities %}
            {% set all_entities = labeled_all_entities('Climate', as_array) %}
            {% set ns = namespace(entities=[]) %}
            {% for entity in states.sensor
              | selectattr('entity_id', 'in', all_entities)
              | selectattr('attributes.device_class', 'eq', 'humidity')
              | rejectattr('state', 'in', ['unknown', 'unavailable', 'none']) %}
              {% set humidity = states(entity.entity_id) | float(-1) %}
              {% if humidity > 70.0 or humidity < 30.0 %}
                {% set ns.entities = ns.entities + [entity.entity_id] %}
              {% endif %}
            {% endfor %}
            {{ ns.entities }}
          message: >
            {% set entities = this.attributes.get('entities', []) %}
            {% set entity_count = entities | count %}
            {% set entity_first = entities | first | default('') %}
            {% if entity_count == 0 %}All zones normal
            {% elif entity_count == 1 %}{{ state_attr(entity_first, 'friendly_name') }} is {{ states(entity_first, rounded=True, with_unit=True) }}
            {% else %}{{ state_attr(entity_first, 'friendly_name') }} ({{ states(entity_first, rounded=True, with_unit=True) }}) and {{ entity_count - 1 }} others are critical warning
            {% endif %}
          source_entity_id: "{{ this.entity_id }}"
          title: "💧 Humidity Warning"

alert:

  p1_climate_temp:
    name: "Climate Temperature CRITICAL"
    entity_id: binary_sensor.p1_climate_temp_trigger
    state: "on"
    can_acknowledge: true
    skip_first: false
    repeat: 30
    notifiers: p1_critical
    title: "{{ state_attr('binary_sensor.p1_climate_temp_trigger', 'title') }}"
    message: "{{ state_attr('binary_sensor.p1_climate_temp_trigger', 'message') }}"
    done_message: >
      Recovered at {{ as_local(states.binary_sensor.p1_climate_temp_trigger.last_changed).strftime('%a %b %-d, %-I:%M %p') }}
    data:
      tag: p1_climate_temp
      group: climate_alerts
      push:
        interruption-level: critical
      actions:
        - action: alert.p1_climate_temp.mute
          title: "Mute"
          icon: "sfsymbols:bell.slash"

  p1_climate_humidity:
    name: "Climate Humidity CRITICAL"
    entity_id: binary_sensor.p1_climate_humidity_trigger
    state: "on"
    repeat: 30
    can_acknowledge: true
    skip_first: false
    notifiers: p1_critical
    title: "{{ state_attr('binary_sensor.p1_climate_humidity_trigger', 'title') }}"
    message: "{{ state_attr('binary_sensor.p1_climate_humidity_trigger', 'message') }}"
    done_message: >
      Recovered at {{ as_local(states.binary_sensor.p1_climate_humidity_trigger.last_changed).strftime('%a %b %-d, %-I:%M %p') }}
    data:
      tag: p1_climate_humidity
      group: climate_alerts
      push:
        interruption-level: critical
      actions:
        - action: alert.p1_climate_humidity.mute
          title: "Mute"
          icon: "sfsymbols:bell.slash"

  p2_climate_temp:
    name: "Climate Temperature Warning"
    entity_id: binary_sensor.p2_climate_temp_trigger
    state: "on"
    repeat: 60
    can_acknowledge: true
    skip_first: false
    notifiers: p2_warning
    title: "{{ state_attr('binary_sensor.p2_climate_temp_trigger', 'title') }}"
    message: "{{ state_attr('binary_sensor.p2_climate_temp_trigger', 'message') }}"
    done_message: >
      Recovered at {{ as_local(states.binary_sensor.p2_climate_temp_trigger.last_changed).strftime('%a %b %-d, %-I:%M %p') }}
    data:
      tag: p2_climate_temp
      group: climate_alerts
      actions:
        - action: alert.p2_climate_temp.mute
          title: "Mute"
          icon: "sfsymbols:bell.slash"

  p2_climate_humidity:
    name: "Climate Humidity Warning"
    entity_id: binary_sensor.p2_climate_humidity_trigger
    state: "on"
    repeat: 60
    can_acknowledge: true
    skip_first: false
    notifiers: p2_warning
    title: "{{ state_attr('binary_sensor.p2_climate_humidity_trigger', 'title') }}"
    message: "{{ state_attr('binary_sensor.p2_climate_humidity_trigger', 'message') }}"
    done_message: >
      Recovered at {{ as_local(states.binary_sensor.p2_climate_humidity_trigger.last_changed).strftime('%a %b %-d, %-I:%M %p') }}
    data:
      tag: p2_climate_humidity
      group: climate_alerts
      actions:
        - action: alert.p2_climate_humidity.mute
          title: "Mute"
          icon: "sfsymbols:bell.slash"
