# Leak Detector
# General
#
# Trigger alerts if any leak detector goes off.
---
#
# Device Configuration
#
homeassistant:
  customize:
    package.node_anchors:
      pkg: &package
        package: general/leak_detector

      leak: &leak
        package: general/leak_detector
        show_as: moisture

    #
    # Leak Sensors
    #
    binary_sensor.basement_bath_leak:
      <<: *leak
      friendly_name: Basement Bath Leak

    binary_sensor.guest_bath_leak:
      <<: *leak
      friendly_name: Guest Bath Leak

    binary_sensor.half_bath_leak:
      <<: *leak
      friendly_name: Half Bath Leak

    binary_sensor.kitchen_dishwasher_leak:
      <<: *leak
      friendly_name: Kitchen Dishwasher Leak

    binary_sensor.kitchen_refrigerator_leak:
      <<: *leak
      friendly_name: Kitchen Refrigerator Leak

    binary_sensor.kitchen_sink_leak:
      <<: *leak
      friendly_name: Kitchen Sink Leak

    binary_sensor.laundry_leak:
      <<: *leak
      friendly_name: Laundry Leak

    binary_sensor.primary_bath_toilet_leak:
      <<: *leak
      friendly_name: Primary Bath Toilet Leak

    binary_sensor.primary_bath_tub_leak:
      <<: *leak
      friendly_name: Primary Bath Tub Leak

    binary_sensor.suite_bath_leak:
      <<: *leak
      friendly_name: Suite Bath Leak

    binary_sensor.utility_drain_leak:
      <<: *leak
      friendly_name: Utility Drain Leak

    binary_sensor.test_leak:
      <<: *leak
      friendly_name: Test Leak

    #
    # Other package items
    #
    alert.p1_leak_detector:
      <<: *package

    binary_sensor.p1_leak_detector_trigger:
      <<: *package

    input_boolean.test_leak:
      <<: *package
      friendly_name: Test Leak

#
# Test Sensor
#
input_boolean:
  test_leak:

#
# Alert Triggers
#
template:

  - binary_sensor:
      - name: test_leak
        state: "{{ states('input_boolean.test_leak') }}"
        device_class: moisture

  - binary_sensor:
      - name: p1_leak_detector_trigger
        state: "{{ this.attributes.devices | count > 0 }}"
        attributes:
          source_entity_id: "binary_sensor.p1_leak_detector_trigger" # self
          devices: >
            {{ states.binary_sensor
              | selectattr('attributes.package', 'eq', 'general/leak_detector')
              | selectattr('attributes.device_class', 'eq', 'moisture')
              | rejectattr('state', 'in', ['unknown', 'unavailable', 'none'])
              | selectattr('state', 'eq', 'on')
              | map(attribute="attributes.friendly_name", default="Unknown")
              | list }}
          title: 💧 Leak Detected
          message: >
            {% set devices_count = this.attributes.devices | count %}
            {% set devices_first = this.attributes.devices | first %}
            {% if devices_count == 0 %}All detectors dry
            {% elif devices_count == 1 %}{{ devices_first }} is wet
            {%- else -%}{{ devices_first }} and {{ devices_count - 1 }} others are wet
            {%- endif -%}

#
# Alerts
#
alert:
  p1_leak_detector:
    name: Leak Detector Alarm
    entity_id: binary_sensor.p1_leak_detector_trigger
    state: "on"
    can_acknowledge: true
    skip_first: false
    notifiers: p1_critical
    repeat:
      - 30
      - 60
    title: "{{ state_attr('binary_sensor.p1_leak_detector_trigger', 'title') }}"
    message: "{{ state_attr('binary_sensor.p1_leak_detector_trigger', 'message') }}"
    done_message: >
      Recovered at {{ as_local(states.binary_sensor.p1_leak_detector_trigger.last_changed).strftime('%a %b %-d, %-I:%M %p') }}
    data:
      tag: p1_leak_detector
      subtitle: Lavender Circle
      group: ha
      url: "/1-system/alerts"
      actions:
        - action: alert.p1_leak_detector.mute
          title: "Mute"
          icon: "sfsymbols:bell.slash"
