# Power Monitor
# General
#
# Monitor UPS status and alert when on battery power
---
#
# Device Configuration
#
homeassistant:
  customize:
    package.node_anchors:
      pkg: &package
        package: general/power_monitor

    #
    # Programmatic entities defined in this package
    #
    alert.p1_ups_on_battery:
      <<: *package
    binary_sensor.p1_ups_on_battery_trigger:
      <<: *package

#
# Alert Triggers
#
template:
  - binary_sensor:

      - name: p1_ups_on_battery_trigger
        state: >
          {{ 'On Battery' in states('sensor.cyberpower_network_ups_status') }}
        availability: >
          {{ not is_state("sensor.cyberpower_network_ups_status", ['unavailable', 'unknown', 'none']) }}
        attributes:
          device_class: problem
          source_entity_id: sensor.cyberpower_network_ups_status
          title: 🔌 Power is out
          message: >
            {% if 'On Battery' in states('sensor.cyberpower_network_ups_status') %}
              UPS is running on battery power ({{ states('sensor.cyberpower_network_ups_battery_charge', rounded=True, with_unit=True) }})
            {%- else -%}
              UPS is operating normally ({{ states('sensor.cyberpower_network_ups_battery_charge', rounded=True, with_unit=True) }})
            {%- endif -%}

#
# Alerts
#
alert:
  p1_ups_on_battery:
    name: UPS On Battery Warning
    entity_id: binary_sensor.p1_ups_on_battery_trigger
    state: "on"
    can_acknowledge: true
    skip_first: false
    notifiers: p1_critical
    repeat: 30
    title: "{{ state_attr('binary_sensor.p1_ups_on_battery_trigger', 'title') }}"
    message: "{{ state_attr('binary_sensor.p1_ups_on_battery_trigger', 'message') }}"
    done_message: >
      Recovered at {{ as_local(states.binary_sensor.p1_ups_on_battery_trigger.last_changed).strftime('%a %b %-d, %-I:%M %p') }}
    data:
      tag: p1_ups_on_battery
      subtitle: Lavender Circle
      group: ha
      url: "/1-system/alerts"
      push:
        interruption-level: critical
      actions:
        - action: alert.p1_ups_on_battery.mute
          title: "Mute"
          icon: "sfsymbols:bell.slash"
