# Back Patio
# Area
---

#
# Device Configuration
#
homeassistant:
  customize:
    package.node_anchors:
      pkg: &package
        package: area/back_patio

    #
    # Programmatic entities defined in this package
    #
    automation.back_patio_auto_lights:
      <<: *package

    automation.back_patio_auto_heat_mats_off:
      <<: *package

    #
    # Sensors needed to function
    #
    switch.back_patio_switch:
      device_monitoring: true
      friendly_name: Back Patio Switch

    switch.back_patio_heat_mats:
      device_monitoring: true
      friendly_name: Back Patio Heat Mats
      icon: mdi:heat-wave

    switch.back_patio_string_lights:
      device_monitoring: true
      friendly_name: Back Patio String Lights
      icon: mdi:string-lights

automation:

  #
  # Sync string lights with switch
  #
  - id: back_patio_auto_lights
    alias: Back Patio Auto Lights
    description: "Toggle the string lighting with the main switch."
    use_blueprint:
      path: auto_link_switch.yaml
      input:
        source_switch: switch.back_patio_switch
        linked_entities:
          - switch.back_patio_string_lights

  #
  # Auto turn off heat mats
  #
  - id: back_patio_auto_heat_mats_off
    alias: Back Patio Auto Heat Mats Off
    description: "Turn off heat mats after 3 hours."
    triggers:
      - trigger: state
        entity_id: switch.back_patio_heat_mats
        to: "on"
        for:
          hours: 3
    actions:
      - action: switch.turn_off
        target:
          entity_id: switch.back_patio_heat_mats
    mode: single