# Back Office
# Area
---
#
# Device Configuration
#
homeassistant:
  customize:
    package.node_anchors:
      pkg: &package
        package: area/back_office
      ety: &entity
        entity_monitor: on

    #
    # Programmatic entities defined in this package
    #
    automation.back_office_auto_lights:
      <<: *package

    #
    # Sensors needed to function
    #
    switch.back_office_lightswitch :
      <<: *entity
    switch.back_office_wall_lights:
      <<: *entity

#
# Automations to sync lighting with switch
#
automation:
  - id: back_office_auto_lights
    alias: Back Office Auto Lights
    description: "Toggle the wall lighting with the main switch."
    use_blueprint:
      path: auto_link_switch.yaml
      input:
        source_switch: switch.back_office_lightswitch
        linked_entities:
          - switch.back_office_wall_lights
