# Back Patio
# Area
---

#
# Device Configuration
#
homeassistant:
  customize:
    package.node_anchors:
      pkg: &package
        package: area/back_patio
      ety: &entity
        entity_monitor: on

    #
    # Programmatic entities defined in this package
    #
    automation.back_patio_auto_lights:
      <<: *package
    automation.back_patio_auto_heat_mats_off:
      <<: *package

    #
    # Sensors needed to function
    #
    switch.back_patio_switch:
      <<: *entity
    switch.back_patio_heat_mats:
      <<: *entity
      icon: mdi:heat-wave
    switch.back_patio_string_lights:
      <<: *entity
      icon: mdi:string-lights

automation:

  #
  # Sync string lights with switch
  #
  - id: back_patio_auto_lights
    alias: Back Patio Auto Lights
    description: "Toggle the string lighting with the main switch."
    use_blueprint:
      path: auto_link_switch.yaml
      input:
        source_switch: switch.back_patio_switch
        linked_entities:
          - switch.back_patio_string_lights

  #
  # Auto turn off heat mats
  #
  - id: back_patio_auto_heat_mats_off
    alias: Back Patio Auto Heat Mats Off
    description: "Turn off heat mats automatically"
    triggers:
      - trigger: state
        entity_id: switch.back_patio_heat_mats
        to: "on"
        for:
          minutes: 90
    actions:
      - action: switch.turn_off
        target:
          entity_id: switch.back_patio_heat_mats
    mode: single