---
### Garage ###

input_boolean:
  ##############################################################################
  garage_double_close_auto_enabled:
    name: Garage Double Auto-Close Enabled
    icon: mdi:garage-variant
  ##############################################################################
  garage_double_open_alert_enabled:
    name: Garage Double Open Alert Enabled
    icon: mdi:garage-alert-variant
  ##############################################################################
  garage_freezer_temp_alert_enabled:
    name: Garage Freezer Alert Enabled
    icon: mdi:fridge-alert
  ################################################################################

automation:
  ##############################################################################
  - id: garage_double_auto_close
    alias: Garage Double Auto Close
    description: "Close double garage door if left open for 10 minutes."
    triggers:
      - trigger: state
        entity_id: cover.konnected_f0f5bd514400_garage_door
        to: "open"
        for:
          hours: 0
          minutes: 10
          seconds: 0
    conditions:
      - condition: state
        entity_id: input_boolean.garage_double_close_auto_enabled
        state: "on"
      - condition: state
        entity_id: lock.konnected_f0f5bd514400_lock
        state: "unlocked"
    actions:
      - action: cover.close_cover
        target:
          entity_id: cover.konnected_f0f5bd514400_garage_door
    mode: single
  ##############################################################################
  - id: garage_double_auto_lights
    alias: Garage Double Auto Lights
    description: "Turn on garage lights when double garage door is open."
    triggers:
      - trigger: state
        entity_id: cover.konnected_f0f5bd514400_garage_door
        to: "opening"
        id: double_garage_door_opening
      - trigger: state
        entity_id: cover.konnected_f0f5bd514400_garage_door
        to: "closed"
        id: double_garage_door_closed
    actions:
      - choose:
          # When door is opening - save current state and turn on lights
          - conditions:
              - condition: trigger
                id: double_garage_door_opening
            sequence:
              - action: scene.create
                data:
                  snapshot_entities:
                    - switch.garage_lights
                    - switch.outside_garage_lights
                  scene_id: garage_lights_previous_state
              - action: switch.turn_on
                target:
                  entity_id:
                    - switch.garage_lights
                    - switch.outside_garage_lights
          # When door is closed - wait 5 minutes then restore previous state
          - conditions:
              - condition: trigger
                id: double_garage_door_closed
            sequence:
              - delay:
                  minutes: 5
              - action: scene.turn_on
                target:
                  entity_id: scene.garage_lights_previous_state
              - action: scene.delete
                target:
                  entity_id: scene.garage_lights_previous_state
    mode: restart

template:
  ##############################################################################
  - binary_sensor:
      - name: Garage Double Open Alert
        state: >
          {{ (states('cover.konnected_f0f5bd514400_garage_door') == 'open') 
            and is_state('input_boolean.garage_double_open_alert_enabled', 'on') 
            and (as_timestamp(now()) - as_timestamp(states.cover.konnected_f0f5bd514400_garage_door.last_changed) > 3600) }} # 3600 = 60 minutes
        availability: "{{ states('cover.konnected_f0f5bd514400_garage_door') not in ['unavailable', 'unknown', 'none'] }}"
  ##############################################################################
  - binary_sensor:
      - name: Garage Freezer Temp Alert
        state: >
          {{ (states('sensor.garage_freezer_monitor_temperature') | int(0) < -10 or states('sensor.garage_freezer_monitor_temperature') | int(0) > 10) 
            and is_state('input_boolean.garage_freezer_temp_alert_enabled', 'on') }}
        availability: "{{ states('sensor.garage_freezer_monitor_temperature') not in ['unavailable', 'unknown', 'none'] }}"
  ##############################################################################

alert:
  ##############################################################################
  garage_double_open_warn_alert_active:
    name: Garage Double Open
    entity_id: binary_sensor.garage_double_open_alert
    state: "on"
    repeat:
      - 60
      - 120
    can_acknowledge: true
    skip_first: false
    title: "(Warn) Garage Door Open"
    message: "Double Garage has been open since {{ states.cover.konnected_f0f5bd514400_garage_door.last_changed.strftime('%a %b %-d, %-I:%M %p') }}"
    done_message: "RESOLVED: Double Garage closed at {{ now().strftime('%a %b %-d, %-I:%M %p') }}"
    notifiers:
      - Warning
  ##############################################################################
  garage_freezer_crit_alert_active:
    name: Garage Freezer Temp
    entity_id: binary_sensor.garage_freezer_temp_alert
    state: "on"
    repeat:
      - 15
      - 30
      - 60
      - 120
    can_acknowledge: true
    skip_first: false
    title: "(CRIT) Garage Freezer Temp"
    message: "Temp is {{ states('sensor.garage_freezer_monitor_temperature') }}° F at {{ as_timestamp(states.sensor.garage_freezer_monitor_temperature.last_changed) | timestamp_custom('%a %b %-d, %-I:%M %p') }}"
    done_message: "RESOLVED Garage Freezer Temp at {{ as_timestamp(states.binary_sensor.garage_freezer_temp_alert.last_changed) | timestamp_custom('%a %b %-d, %-I:%M %p') }}"
    notifiers:
      - Critical
