# Garage
# Area
---

#
# Device Configuration
#
homeassistant:
  customize:
    package.node_anchors:
      pkg: &package
        package: area/garage

    #
    # Programmatic entities defined in this package
    #
    alert.p2_garage_freezer_temp:
      <<: *package
    alert.p2_garage_double_open:
      <<: *package
    binary_sensor.p2_garage_freezer_temp_trigger:
      <<: *package
    binary_sensor.p2_garage_double_open_trigger:
      <<: *package

#
# Alert Triggers
#
template:
  - binary_sensor:

      - name: p2_garage_double_open_trigger
        state: "{{ is_state('cover.garage_double_garage_door', 'open') }}"
        availability: >
          {{ not is_state("cover.garage_double_garage_door", ['unavailable', 'unknown', 'none']) }}
        delay_on:
          minutes: 60
        attributes:
          device_class: problem
          source_entity_id: cover.garage_double_garage_door
          title: 🚗 Garage Door Open (Double)
          message: >
            Open since {{ as_local(states.cover.garage_double_garage_door.last_changed).strftime('%a %b %-d, %-I:%M %p') }}

      - name: p2_garage_single_open_trigger
        state: "{{ is_state('cover.garage_single_garage_door', 'open') }}"
        availability: >
          {{ not is_state("cover.garage_single_garage_door", ['unavailable', 'unknown', 'none']) }}
        delay_on:
          minutes: 60
        attributes:
          device_class: problem
          source_entity_id: cover.garage_single_garage_door
          title: 🚗 Garage Door Open (Single)
          message: >
            Open since {{ as_local(states.cover.garage_single_garage_door.last_changed).strftime('%a %b %-d, %-I:%M %p') }}

      - name: p2_garage_freezer_temp_trigger
        state: >
          {{ states("sensor.garage_freezer_monitor_temperature") | int(0) < -10
            or states("sensor.garage_freezer_monitor_temperature") | int(0) > 20 }}
        availability: >
          {{ not is_state("sensor.garage_freezer_monitor_temperature", ['unavailable', 'unknown', 'none']) }}
        delay_on:
          minutes: 60
        attributes:
          device_class: problem
          source_entity_id: sensor.garage_freezer_monitor_temperature
          title: ❄️ Garage Freezer Temp
          message: >
            Freezer temp at {{ states('sensor.garage_freezer_monitor_temperature', rounded=True, with_unit=True) }}

#
# Alerts
#
alert:

  p2_garage_double_open:
    name: Garage Double Door Open
    entity_id: binary_sensor.p2_garage_double_open_trigger
    state: "on"
    can_acknowledge: true
    skip_first: false
    notifiers: p2_warning
    repeat:
      - 60
      - 120
    title: "{{ state_attr('binary_sensor.p2_garage_double_open_trigger', 'title') }}"
    message: "{{ state_attr('binary_sensor.p2_garage_double_open_trigger', 'message') }}"
    done_message: >
      Recovered at {{ as_local(states.binary_sensor.p2_garage_double_open_trigger.last_changed).strftime('%a %b %-d, %-I:%M %p') }}
    data:
      tag: p2_garage_double_open
      subtitle: Lavender Circle
      group: ha
      url: "/1-system/alerts"
      actions:
        - action: alert.p2_garage_double_open.mute
          title: "Mute"
          icon: "sfsymbols:bell.slash"

  p2_garage_single_open:
    name: Garage Single Door Open
    entity_id: binary_sensor.p2_garage_single_open_trigger
    state: "on"
    can_acknowledge: true
    skip_first: false
    notifiers: p2_warning
    repeat:
      - 60
      - 120
    title: "{{ state_attr('binary_sensor.p2_garage_single_open_trigger', 'title') }}"
    message: "{{ state_attr('binary_sensor.p2_garage_single_open_trigger', 'message') }}"
    done_message: >
      Recovered at {{ as_local(states.binary_sensor.p2_garage_single_open_trigger.last_changed).strftime('%a %b %-d, %-I:%M %p') }}
    data:
      tag: p2_garage_single_open
      subtitle: Lavender Circle
      group: ha
      url: "/1-system/alerts"
      actions:
        - action: alert.p2_garage_single_open.mute
          title: "Mute"
          icon: "sfsymbols:bell.slash"

  p2_garage_freezer_temp:
    name: Garage Freezer Temp
    entity_id: binary_sensor.p2_garage_freezer_temp_trigger
    state: "on"
    can_acknowledge: true
    skip_first: false
    notifiers: p2_warning
    repeat:
      - 60
      - 120
    title: "{{ state_attr('binary_sensor.p2_garage_freezer_temp_trigger', 'title') }}"
    message: "{{ state_attr('binary_sensor.p2_garage_freezer_temp_trigger', 'message') }}"
    done_message: >
      Recovered at {{ as_local(states.binary_sensor.p2_garage_freezer_temp_trigger.last_changed).strftime('%a %b %-d, %-I:%M %p') }}
    data:
      tag: p2_garage_freezer_temp
      subtitle: Lavender Circle
      group: ha
      url: "/1-system/alerts"
      actions:
        - action: alert.p2_garage_freezer_temp.mute
          title: "Mute"
          icon: "sfsymbols:bell.slash"