# Kitchen
# Area
---
#
# Device Configuration
#
homeassistant:
  customize:
    package.node_anchors:
      pkg: &package
        package: area/kitchen

    #
    # Programmatic entities defined in this package
    #
    automation.kitchen_pantry_auto_lights:
      <<: *package

    #
    # Sensors needed to function
    #
    binary_sensor.kitchen_pantry_door:
      device_monitoring: true
      friendly_name: Kitchen Pantry Door

    switch.kitchen_pantry_light_switch:
      device_monitoring: true
      friendly_name: Kitchen Pantry Lights

#
# Automations
#
automation:

  - id: kitchen_pantry_auto_lights
    alias: Kitchen Pantry Auto Lights
    use_blueprint:
      path: auto_door_lights.yaml
      input:
        trigger_sensors: binary_sensor.kitchen_pantry_door
        target_lights: switch.kitchen_pantry_light_switch
        off_delay: 2
        off_idle_delay: 10
