---
### Kitchen ###

input_boolean:
  ################################################################################
  kitchen_refrigerator_alert_enabled:
    name: Kitchen Refrigerator Alert Enabled
    icon: mdi:fridge-alert
  ################################################################################

binary_sensor:
  - platform: template
    sensors:
      kitchen_refrigerator_alert:
        friendly_name: Kitchen Refigerator Alert
        value_template: "{{ (states('sensor.kitchen_refrigerator_sensor_air_temperature') | int(0) < 32 or states('sensor.kitchen_refrigerator_sensor_air_temperature') | int(0) > 39) and is_state('input_boolean.kitchen_refrigerator_alert_enabled', 'on') }}"

template:
  ################################################################################
  - binary_sensor:
      - name: Kitchen Refigerator Alert Active
        state: "{{ (states('sensor.kitchen_refrigerator_sensor_air_temperature') | int(0) < 32 or states('sensor.kitchen_refrigerator_sensor_air_temperature') | int(0) > 39) and is_state('input_boolean.kitchen_refrigerator_alert_enabled', 'on') }}"
        availability: "{{ states('sensor.kitchen_refrigerator_sensor_air_temperature') not in ['unavailable', 'unknown', 'none'] }}"
  ################################################################################

alert:
  ################################################################################
  kitchen_refigerator_crit_alert_active:
    name: Kitchen Refrigerator Alert Active
    entity_id: binary_sensor.kitchen_refrigerator_alert
    state: "on"
    repeat:
      - 15
      - 30
      - 60
      - 120
    can_acknowledge: true
    skip_first: false
    title: "(Critical) Kitchen Refigerator Temperature"
    message: >
      Temperature is {{ states('sensor.kitchen_refrigerator_sensor_air_temperature') }} F \  
      Triggered: {{ as_timestamp(states.binary_sensor.kitchen_refrigerator_sensor_air_temperature.last_changed) | timestamp_custom('%A %I:%M%p (%d-%b-%Y)') }}
    done_message: "(Resolved) Kitchen Refrigerator Temperature at {{ as_timestamp(states.binary_sensor.kitchen_refrigerator_alert.last_changed) | timestamp_custom('%A %I:%M%p (%d-%b-%Y)') }}"
    notifiers:
      - Critical
