# Laundry
# Area
---

homeassistant:
  customize:
    package.node_anchors:
      pkg: &package
        package: area/laundry

    binary_sensor.dryer_status:
      <<: *package
    binary_sensor.washing_machine_status:
      <<: *package

template:
  binary_sensor:

    - name: Washing Machine Status
      unique_id: washing_machine_status
      variables:
        outlet_current: sensor.laundry_washer_outlet_current
      state: >
        {{ states(outlet_current) | float(-1) > 0.5 }}
      delay_off:
        minutes: 7
      icon: >
        {% if this.state %}mdi:washing-machine
        {% else %}mdi:washing-machine-off
        {% endif %}
      availability: >
        {{ states(outlet_current) not in ('unknown', 'unavailable', 'none') }}
      attributes:
        device_class: running

    - name: Dryer Status
      unique_id: dryer_status
      variables:
        outlet_current: sensor.laundry_dryer_outlet_current
      state: >
        {{ states(outlet_current) | float(-1) > 0.5 }}
      delay_on:
        seconds: 30
      delay_off:
        seconds: 30
      icon: >
        {% if this.state %}mdi:tumble-dryer
        {% else %}mdi:tumble-dryer-off
        {% endif %}
      availability: >
        {{ states(outlet_current) not in ('unknown', 'unavailable', 'none') }}
      attributes:
        device_class: running