# Mudroom
# Area
---
#
# Device Configuration
#
homeassistant:
  customize:
    package.node_anchors:
      pkg: &package
        package: area/mudroom
      ety: &entity
        entity_monitor: on

    #
    # Programmatic entities defined in this package
    #
    automation.mudroom_closet_auto_lights:
      <<: *package

    #
    # Sensors needed to function
    #
    binary_sensor.mudroom_closet_door:
      <<: *entity
    switch.mudroom_closet_light_switch:
      <<: *entity

#
# Automations
#
automation:

  - id: mudroom_closet_auto_lights
    alias: Mudroom Closet Auto Lights
    use_blueprint:
      path: auto_door_lights.yaml
      input:
        trigger_sensors: binary_sensor.mudroom_closet_door
        target_lights: switch.mudroom_closet_light_switch
        off_delay: 2
        off_idle_delay: 10
