---
### Mudroom ###

homeassistant:
  customize:
    package.node_anchors:
      mudroom_closet_door: &mudroom_closet_door binary_sensor.mudroom_closet_door
      mudroom_closet_lights: &mudroom_closet_lights switch.mudroom_closet_light_switch

automation:
  ##############################################################################
  - id: mudroom_closet_auto_lights
    alias: Mudroom Closet Auto Lights
    description: >
      Turn on closet lights when door opens, turn off 2 minutes after door
      closes.
    triggers:
      - trigger: state
        entity_id: *mudroom_closet_door
        to: "on"
        id: door_opened
      - trigger: state
        entity_id: *mudroom_closet_door
        to: "off"
        for:
          minutes: 2
        id: door_closed
    actions:
      - choose:
          - conditions:
              - condition: trigger
                id: door_opened
            sequence:
              - action: switch.turn_on
                target:
                  entity_id: *mudroom_closet_lights
          - conditions:
              - condition: trigger
                id: door_closed
            sequence:
              - action: switch.turn_off
                target:
                  entity_id: *mudroom_closet_lights
    mode: restart
  ##############################################################################
  - id: mudroom_closet_lights_auto_off
    alias: Mudroom Closet Lights Auto Off
    description: "Turn off idle closet lights."
    triggers:
      - trigger: state
        entity_id: *mudroom_closet_lights
        to: "on"
        for:
          hours: 1
    actions:
      - action: switch.turn_off
        target:
          entity_id: *mudroom_closet_lights
    mode: restart
