# Theater
# Area
---
#
# Device Configuration
#
homeassistant:
  customize:
    package.node_anchors:
      pkg: &package
        package: area/theater
      ety: &entity
        entity_monitor: on

    #
    # Programmatic entities defined in this package
    #
    automation.theater_auto_pause_lights:
      <<: *package
    automation.theater_auto_playing_lights:
      <<: *package
    automation.theater_auto_off_lights:
      <<: *package
    scene.theater_lights_paused:
      <<: *package
    scene.theater_lights_playing:
      <<: *package
    scene.theater_lights_full:
      <<: *package

    #
    # Sensors needed to function
    #
    media_player.home_theater:
      <<: *entity
    light.theater_main_lights:
      <<: *entity
    light.theater_sconces:
      <<: *entity

#
# Scenes
#
scene:

  - id: theater_lights_paused
    name: Theater Lights Paused
    icon: mdi:pause-circle
    entities:
      light.theater_main_lights :
        state: "on"
        brightness: 25
      light.theater_sconces :
        state: "on"
        brightness: 255

  - id: theater_lights_playing
    name: Theater Lights Playing
    icon: mdi:play-circle
    entities:
      light.theater_main_lights :
        state: "off"
      light.theater_sconces :
        state: "on"
        brightness: 64

  - id: theater_lights_full
    name: Theater Lights Full
    icon: mdi:lightbulb-on
    entities:
      light.theater_main_lights :
        state: "on"
        brightness: 255
      light.theater_sconces :
        state: "off"

#
# Automations
#
automation:

  - id: theater_auto_pause_lights
    alias: Theater Auto Pause Lights
    description: "Set theater-lights-paused scene when Apple TV is paused or idle"
    triggers:
      - trigger: state
        entity_id: media_player.home_theater
        to: "paused"
        for:
          seconds: 2
      - trigger: state
        entity_id: media_player.home_theater
        to: "idle"
        for:
          seconds: 2
    conditions: []
    actions:
      - action: scene.turn_on
        target:
          entity_id: scene.theater_lights_paused
        data:
          transition: 2
    mode: restart

  - id: theater_auto_playing_lights
    alias: Theater Auto Playing Lights
    description: "Set theater-lights-playing scene when Apple TV starts playing content"
    triggers:
      - trigger: state
        entity_id: media_player.home_theater
        to: "playing"
        for:
          seconds: 10
    actions:
      - action: scene.turn_on
        target:
          entity_id: scene.theater_lights_playing
        data:
          transition: 2
    mode: restart

  - id: theater_auto_off_lights
    alias: Theater Auto Off Lights
    description: "Set theater-lights-full scene when Apple TV turns off"
    triggers:
      - trigger: state
        entity_id: media_player.home_theater
        to: "standby"
        not_from: "unknown" # so lights dont come on when it disconnects or reboots
      - trigger: state
        entity_id: media_player.home_theater
        to: "off"
        not_from: "unknown" # so lights dont come on when it disconnects or reboots
    conditions: []
    actions:
      - action: scene.turn_on
        target:
          entity_id: scene.theater_lights_full
        data:
          transition: 2
    mode: restart
