# Home Climate Alert
# Alerts
#
---

homeassistant:
  customize:
    package.node_anchors:
      pkg: &package
        package: alerts/p2_home_climate_alert

    alert.p2_home_climate:
      <<: *package
    binary_sensor.p2_home_climate_trigger:
      <<: *package

template:
  - binary_sensor:
      - name: P2 Home Climate Trigger
        unique_id: p2_home_climate_trigger
        variables:
          label: Home Climate
        state: >
          {{ this.attributes.get('active_entities', []) | count > 0 }}
        delay_on:
          seconds: 10
        availability: >
          {% set labeled_entities = label_entities(label) %}
          {{ states.binary_sensor
            | selectattr('entity_id', 'in', labeled_entities)
            | selectattr('attributes.device_class', 'eq', 'problem')
            | rejectattr('state', 'in', ['unknown', 'unavailable', 'none'])
            | list | count > 0}}
        attributes:
          device_class: problem
          monitored_entities: >
            {% set labeled_entities = label_entities(label) %}
            {{ states.binary_sensor
              | selectattr('entity_id', 'in', labeled_entities)
              | selectattr('attributes.device_class', 'eq', 'problem')
              | map(attribute='entity_id')
              | list }}
          active_entities: >
            {% set labeled_entities = label_entities(label) %}
            {{ states.binary_sensor
              | selectattr('entity_id', 'in', labeled_entities)
              | selectattr('attributes.device_class', 'eq', 'problem')
              | rejectattr('state', 'in', ['unknown', 'unavailable', 'none'])
              | selectattr('state', 'eq', 'on')
              | map(attribute='entity_id')
              | list }}
          title: 🌡️ Home Climate Warning
          message: >
            {% set active_entities = this.attributes.get('active_entities', []) %}
            {% set entity_count = active_entities | count %}
            {% if entity_count == 0 %}
              Home climate normal.
            {% else %}
              {% set entity_first = active_entities | first %}
              {% set entity_source = state_attr(entity_first, 'entity_id') | default(entity_first, true) %}
              {% if entity_count == 1 %}
                {{ state_attr(entity_source, 'friendly_name') }} is {{ state_attr(entity_first, 'position') }} range at {{ states(entity_source, rounded=True, with_unit=True) }}.
              {% else %}
                {{ state_attr(entity_source, 'friendly_name') }} ({{ states(entity_source, rounded=True, with_unit=True) }}) and {{ entity_count - 1 }} others are out of range.
              {% endif %}
            {% endif %}
          source_entity_id: >
            {% set active_entities = this.attributes.get('active_entities', []) %}
            {% if active_entities | count > 0 %}
              {% set entity_first = active_entities | first %}
              {% set entity_source = state_attr(entity_first, 'entity_id') | default(entity_first, true) %}
              {{ entity_source }}
            {% else %}
              {{ this.entity_id }}
            {% endif %}

alert:
  p2_home_climate:
    name: Home Climate
    entity_id: binary_sensor.p2_home_climate_trigger
    state: 'on'
    can_acknowledge: true
    skip_first: false
    notifiers: persistent_notification
    repeat:
      - 1440
    title: >
      {{ state_attr('binary_sensor.p2_home_climate_trigger', 'title') }}
    message: >
      {{ state_attr('binary_sensor.p2_home_climate_trigger', 'message') }}
    done_message: >
      Recovered at {{ as_local(states.binary_sensor.p2_home_climate_trigger.last_changed).strftime('%a %b %-d, %-I:%M %p') }}
    data:
      tag: p2_home_climate
      group: ha
      url: /dashboard-lavender/alerts
      actions:
        - action: alert.p2_home_climate.mute
          title: 'Mute'
          icon: 'sfsymbols:bell.slash'