# Package Alert
# Alerts
#
# Monitor the availability of the entities defined by packages. This helps find
# misconfigurations
---

homeassistant:
  customize:
    package.node_anchors:
      pkg: &package
        package: alerts/p2_package_alert

    alert.p2_package:
      <<: *package
    binary_sensor.p2_package_trigger:
      <<: *package
    # Adding this UI helper to the package for testing
    binary_sensor.test_package_availability:
      <<: *package

template:
  - binary_sensor:
      - name: P2 Package Availability Trigger
        unique_id: p2_package_trigger
        state: >
          {{ this.attributes.get('active_entities', []) | count > 0 }}
        delay_on:
          seconds: 120
        attributes:
          device_class: problem
          monitored_entities: >
            {{ states
              | selectattr('attributes.package', 'defined')
              | map(attribute="entity_id", default="Unknown")
              | list }}
          active_entities: >
            {{ states
              | selectattr('attributes.package', 'defined')
              | selectattr('state', 'in', ['unavailable', 'unknown', 'none'])
              | rejectattr('entity_id', 'eq', 'binary_sensor.p2_package_trigger')
              | map(attribute="entity_id", default="Unknown")
              | list }}
          title: ⚙️ Package entity unavailable
          message: >
            {% set active_entities = this.attributes.get('active_entities', []) %}
            {% set entity_count = active_entities | count %}
            {% if entity_count == 0 %}
              All package entities online.
            {% else %}
              {% set entity_first = active_entities | first %}
              {% if entity_count == 1 %}
                {{ state_attr(entity_first, 'friendly_name') }} is {{ states(entity_first, rounded=True, with_unit=True) }}.
              {% else %}
                {{ state_attr(entity_first, 'friendly_name') }} and {{ entity_count - 1 }} others are unavailable.
              {% endif %}
            {% endif %}
          source_entity_id: >
            {% set active_entities = this.attributes.get('active_entities', []) %}
            {% if active_entities | count > 0 %}
              {{ active_entities | first }}
            {% else %}
              {{ this.entity_id }}
            {% endif %}

alert:
  p2_package:
    name: Package Availability
    entity_id: binary_sensor.p2_package_trigger
    state: "on"
    can_acknowledge: true
    skip_first: false
    notifiers: persistent_notification
    repeat:
      - 1440
    title: >
      {{ state_attr('binary_sensor.p2_package_trigger', 'title') }}
    message: >
      {{ state_attr('binary_sensor.p2_package_trigger', 'message') }}
    done_message: >
      Recovered at {{ as_local(states.binary_sensor.p2_package_trigger.last_changed).strftime('%a %b %-d, %-I:%M %p') }}
    data:
      tag: p2_package
      group: ha
      url: /dashboard-lavender/alerts
      actions:
        - action: alert.p2_package.mute
          title: "Mute"
          icon: "sfsymbols:bell.slash"