# Alerting Tests
# System
#
# Test the alerting setup
---

#
# Device Configuration
#
homeassistant:
  customize:
    package.node_anchors:
      pkg: &package
        package: system/alert_test

    alert.p1_test_alert:
      <<: *package

    alert.p2_test_alert:
      <<: *package

    binary_sensor.p1_test_alert_trigger:
      <<: *package

    binary_sensor.p2_test_alert_trigger:
      <<: *package

    input_boolean.p1_test_alert:
      <<: *package
      friendly_name: Test P1 Alerts

    input_boolean.p2_test_alert:
      <<: *package
      friendly_name: Test P2 Alerts

#
# Test Alert Input
#
input_boolean:

  p1_test_alert:
    name: "P1 Test Alert"
    icon: mdi:alert-box-outline

  p2_test_alert:
    name: "P2 Test Alert"
    icon: mdi:alert-outline

#
# Alert Triggers
#
template:

  - binary_sensor:
      - name: p1_test_alert_trigger
        state: >
          {{ is_state('input_boolean.p1_test_alert', 'on') }}
        availability: on
        attributes:
          source_entity_id: "input_boolean.p1_test_alert"
          title: 🧪 P1 Test Active
          message: >
            {% if this.state %}P1 Test alert is active
            {%- else -%}P1 Test recovered
            {%- endif -%}

  - binary_sensor:
      - name: p2_test_alert_trigger
        state: >
          {{ is_state('input_boolean.p2_test_alert', 'on') }}
        availability: on
        attributes:
          source_entity_id: "input_boolean.p2_test_alert"
          title: 🧪 P2 Test Active
          message: >
            {% if this.state %}P2 Test alert is active
            {%- else -%}P2 Test recovered
            {%- endif -%}

#
# Alerts
#
alert:
  p1_test_alert:
    name: P1 Test Alert
    entity_id: binary_sensor.p1_test_alert_trigger
    state: "on"
    can_acknowledge: true
    skip_first: false
    notifiers: p1_critical
    repeat: 1 # for testing
    title: "{{ state_attr('binary_sensor.p1_test_alert_trigger', 'title') }}"
    message: "{{ state_attr('binary_sensor.p1_test_alert_trigger', 'message') }}"
    done_message: >
      Recovered at {{ as_local(states.binary_sensor.p1_test_alert_trigger.last_changed).strftime('%a %b %-d, %-I:%M %p') }}
    data:
      tag: p1_test_alert
      subtitle: Lavender Circle
      group: ha
      url: "/1-system/alerts"
      push:
        interruption-level: critical
      actions:
        - action: alert.p1_test_alert.mute
          title: "Mute"
          icon: "sfsymbols:bell.slash"

  p2_test_alert:
    name: P2 Test Alert
    entity_id: binary_sensor.p2_test_alert_trigger
    state: "on"
    can_acknowledge: true
    skip_first: false
    notifiers: p2_warning
    repeat: 1 # for testing
    title: "{{ state_attr('binary_sensor.p2_test_alert_trigger', 'title') }}"
    message: "{{ state_attr('binary_sensor.p2_test_alert_trigger', 'message') }}"
    done_message: >
      Recovered at {{ as_local(states.binary_sensor.p2_test_alert_trigger.last_changed).strftime('%a %b %-d, %-I:%M %p') }}
    data:
      tag: p2_test_alert
      subtitle: Lavender Circle
      group: ha
      url: "/1-system/alerts"
      actions:
        - action: alert.p2_test_alert.mute
          title: "Mute"
          icon: "sfsymbols:bell.slash"