# Device Status
# System
#
# Monitor the availability of devices critical to defined automations and alerts.
---
#
# Device Configuration
#
homeassistant:
  customize:
    package.node_anchors:
      pkg: &package
        package: system/device_status

    input_select.test_status:
      <<: *package
      friendly_name: Test Status

#
# Test Sensor
#
input_select:
  test_status:
    options:
      - on
      - "unknown"
    initial: on

#
# Alert Triggers
#
template:
  - binary_sensor:

      - name: p2_device_status_trigger
        state: >
          {{ states
            | selectattr('attributes.package', 'defined')
            | selectattr('state', 'in', ['unavailable', 'unknown', 'none'])
            | list
            | length > 0 }}
        delay_on:
          minutes: 5
        attributes:
          source_entity_id: "binary_sensor.p2_device_status_trigger" # self
          devices: >
            {{ states
              | selectattr('attributes.package', 'defined')
              | selectattr('state', 'in', ['unavailable', 'unknown', 'none'])
              | join(", ", "attributes.friendly_name") }}
          devices_count: >
            {{ this.attributes.devices.split(", ") | count }}
          devices_first: >
            {{ this.attributes.devices.split(", ") | first }}
          message: >
            {% if this.attributes.devices_count | int(0) == 0 %}Everything is online
            {% elif this.attributes.devices_count | int(0) == 1 %}{{ this.attributes.devices_first }} is offline
            {%- else -%}{{ this.attributes.devices_first }} and {{ this.attributes.devices_count | int(0) - 1 }} others are offline
            {%- endif -%}


#
# Alerts
#
alert:

  p2_device_status:
    name: Device Status Warning
    entity_id: binary_sensor.p2_device_status_trigger
    state: "on"
    can_acknowledge: true
    skip_first: false
    notifiers: p2_warning
    repeat:
      - 120
      - 240
    title: ⚠️ Device Offline
    message: >
      ACTIVE: "{{ state_attr('binary_sensor.p2_device_status_trigger', 'message') }}" for {{ relative_time(states.binary_sensor.p2_device_status_trigger.last_changed) }}
      Devices: {{ state_attr('binary_sensor.p2_device_status_trigger', 'device_list') }}
    done_message: >
      DONE: All essential devices are back online as of {{ states.binary_sensor.p2_device_status_trigger.last_changed.strftime('%a %b %-d, %-I:%M %p') }}
    data:
      tag: p2_device_status
      subtitle: Lavender Circle
      group: ha
      url: "/1-system/alerts"
      actions:
        - action: alert.p2_device_status.mute
          title: "Mute"
          icon: "sfsymbols:bell.slash"
