# Device Battery
# System
#
# Monitor the status of device batteries
---
#
# Device Configuration
#
homeassistant:
  customize:
    package.node_anchors:
      pkg: &package
        package: system/device_battery

    alert.p2_device_battery:
      <<: *package

    binary_sensor.p2_device_battery_trigger:
      <<: *package

    sensor.basement_bath_leak_battery:
      <<: *package
      friendly_name: Basement Bath Leak Battery

    sensor.garage_freezer_monitor_battery:
      <<: *package
      friendly_name: Garage Freezer Monitor Battery

    sensor.guest_bath_leak_battery:
      <<: *package
      friendly_name: Guest Bath Leak Battery

    sensor.half_bath_leak_battery:
      <<: *package
      friendly_name: Half Bath Leak Battery

    sensor.kitchen_dishwasher_leak_battery:
      <<: *package
      friendly_name: Kitchen Dishwasher Leak Battery

    sensor.kitchen_pantry_door_battery:
      <<: *package
      friendly_name: Kitchen Pantry Door Battery

    sensor.kitchen_refrigerator_leak_battery:
      <<: *package
      friendly_name: Kitchen Refrigerator Leak Battery

    sensor.kitchen_sink_leak_battery:
      <<: *package
      friendly_name: Kitchen Sink Leak Battery

    sensor.laundry_leak_battery:
      <<: *package
      friendly_name: Laundry Leak Battery

    sensor.mudroom_closet_door_battery:
      <<: *package
      friendly_name: Mudroom Closet Door Battery

    sensor.primary_bath_toilet_leak_battery:
      <<: *package
      friendly_name: Primary Bath Toilet Leak

    sensor.primary_bath_tub_leak_battery:
      <<: *package
      friendly_name: Primary Bath Tub Leak

    sensor.suite_bath_leak_battery:
      <<: *package
      friendly_name: Suite Bath Leak

    sensor.utility_drain_leak_battery:
      <<: *package
      friendly_name: Utility Drain Leak Battery

    sensor.test_battery:
      <<: *package
      friendly_name: Test Battery

    input_number.test_battery:
      <<: *package
      friendly_name: Test Battery

#
# Test Sensor
#
input_number:
  test_battery:
    initial: 100
    max: 100
    min: 0

#
# Alert Triggers
#
template:

  - sensor:
      - name: test_battery
        state: "{{ states('input_number.test_battery') }}"
        device_class: battery

  - binary_sensor:
      - name: p2_device_battery_trigger
        state: "{{ this.attributes.devices | count > 0 }}"
        attributes:
          source_entity_id: "binary_sensor.p2_device_battery_trigger" # self
          devices: >
            {% set ns = namespace(batteries=[]) %}
            {% for entity in states.sensor
              | selectattr('attributes.package', 'eq', 'system/device_battery')
              | selectattr('attributes.device_class', 'eq', 'battery')
              | rejectattr('state', 'in', ['unknown', 'unavailable', 'none']) %}
              {% if entity.state | int(-1) <= 20 and entity.state | int(-1) >= 0 %}
                {% set ns.batteries = ns.batteries + [{
                  'name': entity.attributes.friendly_name | default('Unknown'),
                  'battery': entity.state
                }] %}
              {% endif %}
            {% endfor %}
            {{ ns.batteries }}
          title: 🪫 Device battery low
          message: >
            {% set devices = this.attributes.devices %}
            {% set devices_count = devices | count %}
            {% if devices_count == 0 %}All sensors powered
            {% elif devices_count == 1 %}{{ devices[0].name }} at {{ devices[0].battery }}%
            {%- else -%}{{ devices[0].name }} ({{ devices[0].battery }}%) and {{ devices_count - 1 }} others have low battery
            {%- endif -%}

#
# Alerts
#
alert:
  p2_device_battery:
    name: Device Battery Warning
    entity_id: binary_sensor.p2_device_battery_trigger
    state: "on"
    can_acknowledge: true
    skip_first: false
    notifiers: p2_warning
    repeat:
      - 120
      - 240
    title: "{{ state_attr('binary_sensor.p2_device_battery_trigger', 'title') }}"
    message: "{{ state_attr('binary_sensor.p2_device_battery_trigger', 'message') }}"
    done_message: >
      Recovered at {{ as_local(states.binary_sensor.p2_device_status_trigger.last_changed).strftime('%a %b %-d, %-I:%M %p') }}
    data:
      tag: p2_device_battery
      subtitle: Lavender Circle
      group: ha
      url: "/1-system/alerts"
      actions:
        - action: alert.p2_device_health.mute
          title: "Mute"
          icon: "sfsymbols:bell.slash"
