# Leak Detector
# System
#
# Trigger alerts if any leak detector goes off.
---
#
# Device Configuration
#
homeassistant:
  customize:
    package.node_anchors:
      pkg: &package
        package: system/leak_detector
        show_as: moisture
        leak_detector: True

    binary_sensor.utility_drain_leak:
      <<: *package
      friendly_name: Utility Drain Leak
    binary_sensor.kitchen_sink_leak:
      <<: *package
      friendly_name: Kitchen Sink Leak
    binary_sensor.basement_bath_leak:
      <<: *package
      friendly_name: Basement Bath Leak
#
# Alert Triggers
#
template:
  - binary_sensor:
      - name: p1_leak_detector_trigger
        state: >
          {{ states
            | selectattr('attributes.leak_detector', 'eq', true)
            | selectattr('state', 'eq', 'on')
            | list
            | count | int(0) > 0 }}
        delay_on:
          minutes: 5
        attributes:
          source_entity_id: binary_sensor.p1_leak_detector_trigger # self
          device_count: >
            {{ states
              | selectattr('attributes.leak_detector', 'eq', true)
              | selectattr('state', 'eq', 'on')
              | list
              | count | int(0) }}
          device_first: >
            {{ states
              | selectattr('attributes.leak_detector', 'eq', true)
              | selectattr('state', 'eq', 'on')
              | list
              | map(attribute="attributes.friendly_name") | first }}
          device_list: >
            {{ states
              | selectattr('attributes.leak_detector', 'eq', true)
              | selectattr('state', 'eq', 'on')
              | list
              | map(attribute="attributes.friendly_name") | join(", ") }}
          message: >
            {% if this.attributes.device_count | int(0) == 0 %}Everything is dry
            {% elif this.attributes.device_count | int(0) == 1 %}{{ this.attributes.device_first }} is wet
            {%- else -%}{{ this.attributes.device_first }} and {{ this.attributes.device_count | int(0) - 1 }} others are wet
            {%- endif -%}

#
# Alerts
#
alert:
  p1_leak_detector:
    name: Leak Detector Alarm
    entity_id: binary_sensor.p1_leak_detector_trigger
    state: "on"
    can_acknowledge: true
    skip_first: false
    notifiers: p1_critical
    repeat:
      - 30
      - 60
    title: 💧 Leak Detected
    message: >
      ACTIVE: "{{ state_attr('binary_sensor.p1_leak_detector_trigger', 'message') }}" for {{ relative_time(states.binary_sensor.p1_leak_detector_trigger.last_changed) }}
      Devices: {{ state_attr('binary_sensor.p1_leak_detector_trigger', 'device_list') }}
    done_message: >
      DONE: All dry as of {{ states.binary_sensor.p1_leak_detector_trigger.last_changed.strftime('%a %b %-d, %-I:%M %p') }}
    data:
      tag: p1_leak_detector
      subtitle: Lavender Circle
      group: ha
      url: "/1-system/alerts"
      actions:
        - action: alert.p1_leak_detector.mute
          title: "Mute"
          icon: "sfsymbols:bell.slash"
