# System Monitor
# System
#
# Monitor the health of the Home Assistant system
---

#
# Device Configuration
#
homeassistant:
  customize:
    package.node_anchors:
      pkg: &package
        package: system/system_monitor
      ety: &entity
        entity_monitor: on

    #
    # Programmatic entities defined in this package
    #
    alert.p2_system_entities:
      <<: *package
    alert.p2_system_monitor:
      <<: *package
    binary_sensor.p2_system_entities_trigger:
      <<: *package
    binary_sensor.p2_system_monitor_trigger:
      <<: *package

    #
    # Sensors needed to function
    #
    sensor.system_monitor_disk_usage:
      <<: *entity
    sensor.system_monitor_memory_usage:
      <<: *entity
    sensor.system_monitor_processor_temperature:
      <<: *entity
    sensor.system_monitor_processor_use:
      <<: *entity

#
# Alert Triggers
#
template:
  - binary_sensor:

    - name: p2_system_monitor_trigger
      state: "{{ this.attributes.get('entities', []) | count > 0 }}"
      attributes:
        device_class: problem
        entities: >
          {% set problems = [] %}
          {% if states("sensor.system_monitor_disk_usage") | float(0) > 80 %}
            {% set problems = problems + ['sensor.system_monitor_disk_usage'] %}
          {% endif %}
          {% if states("sensor.system_monitor_memory_usage") | float(0) > 80 %}
            {% set problems = problems + ['sensor.system_monitor_memory_usage'] %}
          {% endif %}
          {% if states("sensor.system_monitor_processor_use") | float(0) > 80 %}
            {% set problems = problems + ['sensor.system_monitor_processor_use'] %}
          {% endif %}
          {% if states("sensor.system_monitor_processor_temperature") | float(0) > 150 %}
            {% set problems = problems + ['sensor.system_monitor_processor_temperature'] %}
          {% endif %}
          {{ problems }}
        source_entity_id: "{{ this.entity_id }}"
        title: 🖥️ System problem
        message: >
          {% set entities = this.attributes.get('entities', []) %}
          {% set entity_count = entities | count %}
          {% set entity_first = entities | first %}
          {% if entity_count == 0 %}All entities okay
          {% elif entity_count == 1 %}{{ entity_first }} is {{ states(entity_first, rounded=True, with_unit=True) }}
          {%- else -%}{{ entity_first }} and {{ entity_count - 1 }} others are having problems
          {%- endif -%}

    - name: p2_system_entities_trigger
      state: "{{ this.attributes.get('entities', []) | count > 0 }}"
      attributes:
        device_class: problem
        source_entity_id: "{{ this.entity_id }}"
        entities: >
          {{ states
            | selectattr('attributes.package', 'defined')
            | selectattr('state', 'in', ['unavailable', 'unknown', 'none'])
            | rejectattr('entity_id', 'eq', 'binary_sensor.p2_system_entities_trigger')
            | map(attribute="entity_id", default="Unknown")
            | list }}
        title: ⚙️ Entity unavailable
        message: >
          {% set devices = this.attributes.get('devices', []) %}
          {% set devices_count = devices | count %}
          {% set devices_first = devices | first %}
          {% if devices_count == 0 %}All entities online
          {% elif devices_count == 1 %}{{ devices_first }} is unavailable
          {%- else -%}{{ devices_first }} and {{ devices_count - 1 }} others are unavailable
          {%- endif -%}


#
# Alerts
#
alert:
  p2_system_monitor:
    name: System Monitor Warning
    entity_id: binary_sensor.p2_system_monitor_trigger
    state: "on"
    can_acknowledge: true
    skip_first: false
    notifiers: p2_warning
    repeat:
      - 60
      - 120
    title: "{{ state_attr('binary_sensor.p2_system_monitor_trigger', 'title') }}"
    message: "{{ state_attr('binary_sensor.p2_system_monitor_trigger', 'message') }}"
    done_message: >
      Recovered at {{ as_local(states.binary_sensor.p2_system_monitor_trigger.last_changed).strftime('%a %b %-d, %-I:%M %p') }}
    data:
      tag: p2_system_monitor
      subtitle: Lavender Circle
      group: ha
      url: "/1-system/alerts"
      actions:
        - action: alert.p2_system_monitor.mute
          title: "Mute"
          icon: "sfsymbols:bell.slash"

  p2_system_entities:
    name: System Entities Warning
    entity_id: binary_sensor.p2_system_entities_trigger
    state: "on"
    can_acknowledge: true
    skip_first: false
    notifiers: p2_warning
    repeat:
      - 60
      - 120
    title: "{{ state_attr('binary_sensor.p2_system_entities_trigger', 'title') }}"
    message: "{{ state_attr('binary_sensor.p2_system_entities_trigger', 'message') }}"
    done_message: >
      Recovered at {{ as_local(states.binary_sensor.p2_system_entities_trigger.last_changed).strftime('%a %b %-d, %-I:%M %p') }}
    data:
      tag: p2_system_entities
      subtitle: Lavender Circle
      group: ha
      url: "/1-system/alerts"
      actions:
        - action: alert.p2_system_entities.mute
          title: "Mute"
          icon: "sfsymbols:bell.slash"