# System Monitor
# System
#
# Monitor the health of the Home Assistant system
---

#
# Device Configuration
#
homeassistant:
  customize:
    package.node_anchors:
      pkg: &package
        package: system/system_monitor

    #
    # Programmatic entities defined in this package
    #
    alert.p2_system_entities:
      <<: *package
    alert.p2_system_monitor:
      <<: *package
    binary_sensor.p2_system_entities_trigger:
      <<: *package
    binary_sensor.p2_system_monitor_trigger:
      <<: *package

template:
  - binary_sensor:

    #
    # Monitor the state of home assistant itself.
    #
    - name: p2_system_monitor_trigger
      state: "{{ this.attributes.get('entities', []) | count > 0 }}"
      availability: >
        {{ states.sensor
          | selectattr('entity_id', 'in', [
            'sensor.system_monitor_disk_usage',
            'sensor.system_monitor_memory_usage',
            'sensor.system_monitor_processor_use',
            'sensor.system_monitor_processor_temperature'])
          | rejectattr('state', 'in', ['unknown', 'unavailable', 'none'])
          | list | count == 4 }}
      attributes:
        device_class: problem
        entities: >
          {% set problems = [] %}
          {% if states("sensor.system_monitor_disk_usage") | float(1000) > 80 %}
            {% set problems = problems + ['sensor.system_monitor_disk_usage'] %}
          {% endif %}
          {% if states("sensor.system_monitor_memory_usage") | float(1000) > 80 %}
            {% set problems = problems + ['sensor.system_monitor_memory_usage'] %}
          {% endif %}
          {% if states("sensor.system_monitor_processor_use") | float(1000) > 80 %}
            {% set problems = problems + ['sensor.system_monitor_processor_use'] %}
          {% endif %}
          {% if states("sensor.system_monitor_processor_temperature") | float(1000) > 150 %}
            {% set problems = problems + ['sensor.system_monitor_processor_temperature'] %}
          {% endif %}
          {{ problems }}
        message: >
          {% set entities = this.attributes.get('entities', []) %}
          {% set entity_count = entities | count %}
          {% set entity_first = entities | first | default('') %}
          {% if entity_count == 0 %}All entities okay
          {% elif entity_count == 1 %}{{ state_attr(entity_first, 'friendly_name') }} is {{ states(entity_first, rounded=True, with_unit=True) }}
          {% else %}{{ state_attr(entity_first, 'friendly_name') }} and {{ entity_count - 1 }} others are having problems
          {% endif %}
        source_entity_id: "{{ this.entity_id }}"
        title: 🖥️ System problem

    #
    # Check that all the system entities (automations, alerts, templates) defined
    # in packages remain available
    #
    - name: p2_system_entities_trigger
      state: "{{ this.attributes.get('entities', []) | count > 0 }}"
      delay_on:
        minutes: 5
      availability: >
        {{ states
          | selectattr('attributes.package', 'defined')
          | rejectattr('state', 'in', ['unknown', 'unavailable', 'none'])
          | list | count > 0 }}
      attributes:
        device_class: problem
        entities: >
          {{ states
            | selectattr('attributes.package', 'defined')
            | selectattr('state', 'in', ['unavailable', 'unknown', 'none'])
            | rejectattr('entity_id', 'eq', 'binary_sensor.p2_system_entities_trigger')
            | map(attribute="entity_id", default="Unknown")
            | list }}
        message: >
          {% set entities = this.attributes.get('entities', []) %}
          {% set entity_count = entities | count %}
          {% set entity_first = entities | first | default('') %}
          {% if entity_count == 0 %}All entities online
          {% elif entity_count == 1 %}{{ state_attr(entity_first, 'friendly_name') }} is unavailable
          {% else %}{{ state_attr(entity_first, 'friendly_name') }} and {{ entity_count - 1 }} others are unavailable
          {% endif %}
        title: ⚙️ System Entity unavailable
        source_entity_id: "{{ this.entity_id }}"

#
# Alerts
#
alert:
  p2_system_monitor:
    name: System Monitor Warning
    entity_id: binary_sensor.p2_system_monitor_trigger
    state: "on"
    can_acknowledge: true
    skip_first: false
    notifiers: p2_warning
    repeat: 60
    title: "{{ state_attr('binary_sensor.p2_system_monitor_trigger', 'title') }}"
    message: "{{ state_attr('binary_sensor.p2_system_monitor_trigger', 'message') }}"
    done_message: >
      Recovered at {{ as_local(states.binary_sensor.p2_system_monitor_trigger.last_changed).strftime('%a %b %-d, %-I:%M %p') }}
    data:
      tag: p2_system_monitor
      subtitle: Lavender Circle
      group: ha
      url: "/1-system/alerts"
      actions:
        - action: alert.p2_system_monitor.mute
          title: "Mute"
          icon: "sfsymbols:bell.slash"

  p2_system_entities:
    name: System Entities Warning
    entity_id: binary_sensor.p2_system_entities_trigger
    state: "on"
    can_acknowledge: true
    skip_first: false
    notifiers: p2_warning
    repeat: 60
    title: "{{ state_attr('binary_sensor.p2_system_entities_trigger', 'title') }}"
    message: "{{ state_attr('binary_sensor.p2_system_entities_trigger', 'message') }}"
    done_message: >
      Recovered at {{ as_local(states.binary_sensor.p2_system_entities_trigger.last_changed).strftime('%a %b %-d, %-I:%M %p') }}
    data:
      tag: p2_system_entities
      subtitle: Lavender Circle
      group: ha
      url: "/1-system/alerts"
      actions:
        - action: alert.p2_system_entities.mute
          title: "Mute"
          icon: "sfsymbols:bell.slash"